### ISSUE TITLE
TextEditor.onDidChangeScrollTop -version 0.2.3

### ISSUE THREAD

**Issue by trunghieu7393** [georgebrindeiro/scroll-sync#27] opened 2017-07-04 03:26 UTC
TextEditor.onDidChangeScrollTop - <embedded>:2945:18
<unknown> - /Users/trunghieu7393/.atom/packages/scroll-sync/lib/scroll-sync.coffee:120:57
ScrlSync.startTracking - /Users/trunghieu7393/.atom/packages/scroll-sync/lib/scroll-sync.coffee:124:17
atom-workspace.subToggle.add.atom.commands.add.scroll-sync:toggle - /Users/trunghieu7393/.atom/packages/scroll-sync/lib/scroll-sync.coffee:31:28
CommandRegistry.handleCommandEvent - <embedded>:18901:35
handleCommandEvent - <embedded>:18639:65

i'm using atom version 1.18.0

**Comment by georgebrindeiro-vtex** [comment] 2017-07-04 12:12
Hi @trunghieu7393! I just released this version yesterday and I'm using Atom 1.18.0. I'll look into the error, but could you give me some more info about the issue so I can replicate the error?

1. How did you activate ScrlSync?
2. What other packages do you have active?
3. What is your OS version?
4. Anything else you might find relevant

**Comment by georgebrindeiro-vtex** [comment] 2017-07-04 14:44
I just took a look at the source code around the lines that led to the error. The issue seems to be related to the textChanged generator function, which creates a map of the corresponding lines for each pane. Could you also share the files that were open in each pane for testing?

**Comment by trunghieu7393** [comment] 2017-07-06 01:20
@georgebrindeiro 
How did you activate ScrlSync?
 - 2 ways:
  + use shortcut
  + active by package menu

What other packages do you have active?
 - i'm sorry, i can't remember that.

What is your OS version?
 - i am using macOS sierra 10.12.5

Could you also share the files that were open in each pane for testing?
 - i can't do that. that is real project :(

do you need other info?

**Comment by georgebrindeiro-vtex** [comment] 2017-07-06 14:15
Unfortunately yes, as I am not able to reproduce your error. Could you fill in this template?

### Description

[Description of the issue]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

atom 1.18.0
scroll-sync 2.3.0
macOS sierra 10.12.5

### Additional Information

[Any additional information, configuration or data that might be necessary to reproduce the issue.]

**Comment by georgebrindeiro-vtex** [comment] 2017-11-07 13:39
@trunghieu7393 are you still facing this issue?

**Comment by trunghieu7393** [comment] 2017-11-08 07:12
@georgebrindeiro i'm using atom version 1.21.1 and i can scroll sync two files.

**Comment by georgebrindeiro-vtex** [comment] 2017-11-13 20:02
Since the issue isn't relevant any more, I'm closing it. Thanks!

**Closed as completed by georgebrindeiro-vtex** 2017-11-13 20:02 UTC
Labels: bug
