### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by hitobashira** [georgebrindeiro/scroll-sync#28] opened 2017-07-06 16:24 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Linux Mint
**Thrown From**: [scroll-sync](https://github.com/georgebrindeiro/scroll-sync) package 0.2.3

### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /home/ehhen/.atom/packages/scroll-sync/lib/scroll-sync.coffee:58

TypeError: Cannot read property 'getBuffer' of undefined
    at /packages/scroll-sync/lib/scroll-sync.coffee:58:22
    at ScrlSync.startTracking (/packages/scroll-sync/lib/scroll-sync.coffee:47:5)
    at /packages/scroll-sync/lib/scroll-sync.coffee:21:30)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:265:35)
    at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:65)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:166:25)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/opt/atom/resources/app/src/atom-environment.js:1314:34)
    at EventEmitter.outerCallback (/opt/atom/resources/app/src/application-delegate.js:334:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
  3x -2:00.8.0 core:move-right (input.hidden-input)
     -1:57.2.0 custom:shift-delete (input.hidden-input)
  3x -1:56.6.0 core:move-right (input.hidden-input)
  2x -1:54.6.0 core:backspace (input.hidden-input)
     -1:51 custom:shift-delete (input.hidden-input)
  3x -1:50.4.0 core:move-right (input.hidden-input)
     -1:46.6.0 custom:shift-delete (input.hidden-input)
  6x -1:45.3.0 core:move-left (input.hidden-input)
     -1:43.8.0 core:delete (input.hidden-input)
 18x -1:43.4.0 core:move-left (input.hidden-input)
     -1:40.8.0 core:delete (input.hidden-input)
 10x -1:35.4.0 core:move-left (input.hidden-input)
 14x -1:30.4.0 core:move-right (input.hidden-input)
     -1:26.4.0 core:move-up (input.hidden-input)
 12x -1:26.1.0 core:move-right (input.hidden-input)
     -0:12.4.0 scroll-sync:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-clock 0.1.12 
atom-copy-on-select 1.4.0 
atom-i18n 0.9.2 
atomic-emacs 0.11.0 
autocomplete-python 1.9.1 
block-cursor 0.13.2 
browser-plus 0.0.97 
charcode-display 0.2.1 
clip-history 0.4.0 
clipboard-plus 0.5.1 
disable-keybindings 0.6.0 
fancy-bracket-matcher 1.0.1 
file-icons 2.1.8 
file-types 0.5.5 
find-selection 0.16.0 
foldingtext-markdown 1.3.2 
highlight-column 0.5.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
japan-util 0.2.0 
japanese-menu 1.13.0 
japanese-word-selection 0.4.0 
language-markdown 0.23.0 
language-regexp 1.0.1 
language-sphinx 0.1.6 
markdown-pdf 1.5.4 
markdown-preview-plus 2.4.10 
markdown-scroll-sync 2.1.2 
markdown-themeable-pdf 1.2.0 
markdown-writer 2.6.5 
minimap 4.28.2 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
open-recent 5.0.0 
pdf-view 0.59.0 
scroll-sync 0.2.3 
shebang-set-grammar 0.6.0 
shell-it 0.2.1 
sphinx-preview 0.1.1 
split-diff 1.4.3 
vz-buffer 0.1.0 
```

**Comment by georgebrindeiro-vtex** [comment] 2017-07-06 16:44
@hitobashira Could you provide a clearer description, besides the stack trace, of the error and how I could reproduce it?

**Comment by georgebrindeiro-vtex** [comment] 2017-11-07 13:38
@hitobashira Are you still facing this issue?

**Comment by georgebrindeiro-vtex** [comment] 2017-11-13 20:01
Since the issue could not be replicated, I'm closing it.

**Closed as completed by georgebrindeiro-vtex** 2017-11-13 20:01 UTC
Labels: bug

**Comment by effektsvk** [comment] 2017-11-18 17:28
Hello, I've managed to reproduce the issue. It happens when you toggle Scroll Sync with the Atom Settings tab and any other file. Here is a stack trace:

[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.21.1 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.12.6
**Thrown From**: [scroll-sync](https://github.com/georgebrindeiro/scroll-sync) package 0.2.4


### Stack Trace

Uncaught TypeError: Cannot read property 'getBuffer' of undefined

```
At /Users/erik/.atom/packages/scroll-sync/lib/scroll-sync.coffee:93

TypeError: Cannot read property 'getBuffer' of undefined
    at ScrlSync.addPaneInfo (/packages/scroll-sync/lib/scroll-sync.coffee:93:20)
    at ScrlSync.startTracking (/packages/scroll-sync/lib/scroll-sync.coffee:73:6)
    at ScrlSync.toggleTracking (/packages/scroll-sync/lib/scroll-sync.coffee:47:8)
    at /packages/scroll-sync/lib/scroll-sync.coffee:35:49)
```

### Commands

```
  2x -3:14.1.0 toggl-client:toggle (div.package-detail.panels-item)
  2x -2:35.6.0 datatip:toggle (input.hidden-input)
     -1:42.9.0 pane:show-item-1 (input.hidden-input)
     -1:42.3.0 pane:show-item-2 (input.hidden-input)
     -1:41.4.0 window:focus-next-pane (input.hidden-input)
     -1:40.9.0 pane:show-item-1 (div.package-detail.panels-item)
     -1:35 pane:show-item-2 (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.7 
autoclose-html 0.23.0 
backspace-until-not-whitespace 0.1.8 
close-on-left 0.9.2 
file-header 1.13.7 
file-icons 2.1.13 
haskell-grammar 0.4.0 
highlight-selected 0.13.1 
language-babel 2.79.0 
language-graphql 0.9.0 
language-haskell 1.14.3 
language-ini 1.19.0 
language-lua 0.9.11 
language-ocaml 1.9.5 
language-rust 0.4.12 
language-swift 0.5.0 
language-thrift 1.0.2 
linter-js-standard 4.0.3 
MagicPython 1.0.12 
minimap 4.29.7 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
nuclide 0.267.0 
nuclide-format-js 0.0.41 
pigments 0.40.2 
scroll-sync 0.2.4 
set-syntax 0.4.0 
sort-lines 0.18.0 
toggl 0.6.0 
toggl-client 0.0.0 
tool-bar 1.1.0 
tree-view-copy-relative-path 1.2.0 
```

**Comment by delize** [comment] 2018-02-15 21:23
I am also experiencing this issue: 

```
Uncaught TypeError: Cannot read property 'getBuffer' of undefined
/Users/adoering/.atom/packages/scroll-sync/lib/scroll-sync.coffee:93
Hide Stack Trace
TypeError: Cannot read property 'getBuffer' of undefined
    at ScrlSync.addPaneInfo (/Users/adoering/.atom/packages/scroll-sync/lib/scroll-sync.coffee:93:20)
    at ScrlSync.startTracking (/Users/adoering/.atom/packages/scroll-sync/lib/scroll-sync.coffee:73:6)
    at ScrlSync.toggleTracking (/Users/adoering/.atom/packages/scroll-sync/lib/scroll-sync.coffee:47:8)
    at HTMLElement.disposables.add.atom.commands.add.scroll-sync:toggle (/Users/adoering/.atom/packages/scroll-sync/lib/scroll-sync.coffee:18:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

**Comment by michaelbaly** [comment] 2019-06-25 09:38
my experience just the same as above, anyone knows how to solve the problem?
