### ISSUE TITLE
Uncaught TypeError: Cannot read property 'dispose' of undefined

### ISSUE THREAD

**Issue by UnConundrum** [georgebrindeiro/scroll-sync#31] opened 2018-02-13 14:36 UTC
[Enter steps to reproduce:]

1. ...Clicked on Packages -> Toggle Scroll Sync
2. ...

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [scroll-sync](https://github.com/georgebrindeiro/scroll-sync) package 0.2.4

### Stack Trace

Uncaught TypeError: Cannot read property 'dispose' of undefined

```
At /Users/wprince/.atom/packages/scroll-sync/lib/scroll-sync.coffee:205

TypeError: Cannot read property 'dispose' of undefined
    at ScrlSync.stopTracking (/packages/scroll-sync/lib/scroll-sync.coffee:205:25)
    at ScrlSync.startTracking (/packages/scroll-sync/lib/scroll-sync.coffee:67:8)
    at ScrlSync.toggleTracking (/packages/scroll-sync/lib/scroll-sync.coffee:47:8)
    at /packages/scroll-sync/lib/scroll-sync.coffee:18:8)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:388:36)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/src/atom-environment.js:1393:34)
    at EventEmitter.outerCallback (/Applications/Atom.app/Contents/Resources/app/src/application-delegate.js:335:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -4:41.9.0 git-plus:fetch-all (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dark-plus-syntax.theme-one-dark-ui)
     -3:59.9.0 core:save (input.hidden-input)
  6x -3:21.7.0 core:backspace (input.hidden-input)
     -2:41.9.0 git-plus:fetch-all (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dark-plus-syntax.theme-one-dark-ui)
     -2:27 core:close (div.github-FilePatchView.is-unstaged)
     -0:41.9.0 git-plus:fetch-all (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-dark-plus-syntax.theme-one-dark-ui)
     -0:16.1.0 scroll-sync:toggle (input.hidden-input)
```

### Non-Core Packages

```
2-dark-syntax 1.1.0 
angularjs 0.5.3 
ask-stack 2.2.0 
atom-beautify 0.30.9 
atom-dark-plus-ui 0.55.0 
atom-live-server 2.2.0 
auto-detect-indentation 1.3.0 
busy-signal 1.4.3 
city-lights-syntax 1.1.6 
copy-filename 1.1.0 
dark-flat-ui 1.2.4 
dark-plus-syntax 2.5.0 
file-icons 2.1.16 
format-shell 2.0.0 
ghar-dark-syntax 2.0.0 
git-plus 7.10.0 
git-plus-toolbar 1.0.1 
gitlab 0.1.3-7 
goto-definition 1.3.4 
highlight-line 0.12.0 
highlight-selected 0.13.1 
intentions 1.1.5 
linter 2.2.0 
linter-rails-best-practices 0.2.2 
linter-ruby 1.2.6 
linter-ui-default 1.6.10 
mc-dark-syntax 1.7.1 
multiline-tab 0.2.1 
pear-dark-syntax 1.0.6 
pigments 0.40.2 
print-atom 0.1.1 
rails-finder 0.8.0 
rails-snippets 2.17.0 
remote-ftp 2.1.4 
scroll-color 0.3.0 
scroll-sync 0.2.4 
snow-dark-syntax 0.1.1 
split-diff 1.5.2 
tab-smart-sort 0.3.0 
tool-bar 1.1.6 
tree-ignore 0.6.2 
tree-view-copy-relative-path 1.2.0 
zhk-dark-syntax 0.3.1 
```

**Comment by georgebrindeiro-vtex** [comment] 2018-03-19 21:09
Hi @UnConundrum, I was able to replicate your bug, I think. It seems like you might not have two editor panes open? Your screen should look like ![this](https://user-images.githubusercontent.com/2094877/37622449-6280842e-2ba0-11e8-9615-9af4088c2dd2.png) when using scroll-sync. 

If that's the case, it's not a bug - there's a clear error message asking you to "Open exactly 2 panes" that comes along with the error you reported. For now I'm closing this issue, but let me know if you're having some other problem.

**Closed as completed by georgebrindeiro-vtex** 2018-03-19 21:09 UTC
Labels: invalid, wontfix
